version: '{build}'

branches:
  only:
  - master

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: "Visual Studio 15 2017"
    ARCH: 32
    BOOST: 1_65_1
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: "Visual Studio 15 2017 Win64"
    ARCH: 64
    BOOST: 1_65_1

clone_script:
- cmd: git clone --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -q %APPVEYOR_REPO_COMMIT%
- cmd: git submodule update --init
    
build_script:
- ps: |
    mkdir build
    cd build
    cmake -D BUILD_CLAR=OFF -D BUILD_EXAMPLES=OFF -D USE_BOOST=ON -D BOOST_ROOT="C:\Libraries\boost_$env:BOOST" .. -G"$env:GENERATOR"
    cmake --build . --config Debug
